"use client";

import { useEffect, useState } from "react";
import { Database, Flag, KeyRound, Search, ShieldCheck, Users } from "lucide-react";
import { Button, PageHeader, SectionTitle, TextInput } from "@/components/ui";
import { useAuth } from "@/lib/auth-store";

type Tab = "users" | "reserved" | "badges" | "premium" | "reports" | "flags" | "bakaboost" | "themes" | "audit";
const tabs: Array<[Tab, string]> = [["users", "Users"], ["reserved", "Reserved names"], ["badges", "Badges"], ["premium", "Premium"], ["reports", "Reports"], ["flags", "Feature flags"], ["bakaboost", "BakaBoost"], ["themes", "Themes"], ["audit", "Audit logs"]];

async function api(path: string, init?: RequestInit) {
  const response = await fetch(`/api/v1/admin${path}`, { ...init, credentials: "include", headers: { "Content-Type": "application/json", ...(init?.headers || {}) } });
  const body = await response.json().catch(() => ({})) as { detail?: string; error?: string };
  if (!response.ok) throw new Error(body.detail || body.error || "Admin request failed.");
  return body as Record<string, any>;
}

export function AdminView() {
  const { user, isReady } = useAuth();
  const [tab, setTab] = useState<Tab>("users");
  if (!isReady) return <main className="mx-auto max-w-[1200px] px-5 py-12 text-zinc-500">Loading admin tools…</main>;
  if (!user?.isAdmin) return <main className="mx-auto max-w-[900px] px-5 py-16"><div className="surface rounded-2xl p-8 text-center"><ShieldCheck className="mx-auto mb-4 text-red-300" /><h1 className="text-xl font-semibold">Administrator access required</h1><p className="mt-2 text-sm text-zinc-500">This area is protected by server-side authorization.</p></div></main>;
  return <main className="mx-auto min-h-screen max-w-[1400px] px-5 py-8 sm:px-8 sm:py-11 xl:px-12"><PageHeader eyebrow="Administration" title="Admin control center" description="Manage account state and platform configuration with an audit trail." /><div className="mb-8 flex flex-wrap gap-2">{tabs.map(([id, label]) => <button key={id} type="button" onClick={() => setTab(id)} className={`rounded-xl border px-3 py-2 text-xs ${tab === id ? "border-[#9b87f5]/50 bg-[#9b87f5]/15 text-white" : "border-white/[.08] text-zinc-500 hover:text-white"}`}>{label}</button>)}</div>{tab === "users" && <UsersPanel />}{tab === "reserved" && <ReservedPanel />}{tab === "badges" && <BadgesPanel />}{tab === "premium" && <PremiumPanel />}{tab === "reports" && <ReportsPanel />}{tab === "flags" && <FlagsPanel />}{tab === "bakaboost" && <BakaBoostPanel />}{tab === "themes" && <ThemesPanel />}{tab === "audit" && <AuditPanel />}</main>;
}

function UsersPanel() {
  const [search, setSearch] = useState(""); const [items, setItems] = useState<any[]>([]); const [error, setError] = useState("");
  const load = () => void api(`/users?search=${encodeURIComponent(search)}`).then((r) => setItems(r.users || [])).catch((e) => setError(e.message)); useEffect(load, []);
  const suspend = async (item: any) => { const suspended = !item.suspended_at; if (!window.confirm(`${suspended ? "Suspend" : "Unsuspend"} this user?`)) return; try { await api(`/users/${item.id}/suspension`, { method: "PATCH", body: JSON.stringify({ suspended, reason: suspended ? "Administrative action" : null }) }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Update failed."); } };
  return <section><SectionTitle icon={Users} title="Users" description="Search by user ID, username, or verified email." /><div className="mb-4 flex gap-2"><div className="relative max-w-lg flex-1"><Search size={15} className="absolute left-3 top-3.5 text-zinc-600" /><TextInput value={search} onChange={setSearch} placeholder="Search users" className="pl-9" /></div><Button variant="accent" onClick={load}>Search</Button></div>{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="surface overflow-x-auto rounded-2xl"><table className="w-full min-w-[780px] text-left text-xs"><thead className="border-b border-white/[.06] text-zinc-600"><tr><th className="p-4">User</th><th className="p-4">Email</th><th className="p-4">Providers</th><th className="p-4">State</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y divide-white/[.06]">{items.map((item) => <tr key={item.id}><td className="p-4"><p className="text-zinc-200">@{item.username || "unclaimed"}</p><p className="mt-1 font-mono text-[10px] text-zinc-600">{item.id}</p></td><td className="p-4 text-zinc-400">{item.email || "—"}</td><td className="p-4 text-zinc-500">{Object.entries(item.providers || {}).filter(([, value]) => value).map(([key]) => key).join(", ") || "email"}</td><td className="p-4">{item.suspended_at ? <span className="text-red-300">Suspended</span> : <span className="text-emerald-400">Active</span>}</td><td className="p-4"><Button variant="ghost" className="h-8 min-h-0 px-2 text-xs" onClick={() => void suspend(item)}>{item.suspended_at ? "Unsuspend" : "Suspend"}</Button></td></tr>)}</tbody></table>{!items.length && <p className="p-8 text-center text-xs text-zinc-600">No users found.</p>}</div></section>;
}

function ReservedPanel() { const [items, setItems] = useState<any[]>([]); const [username, setUsername] = useState(""); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const load = () => void api("/reserved-usernames").then((r) => setItems(r.reserved || [])).catch((e) => setError(e.message)); useEffect(load, []); const add = async () => { try { await api("/reserved-usernames", { method: "POST", body: JSON.stringify({ username, reason }) }); setUsername(""); setReason(""); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not reserve username."); } }; const remove = async (value: string) => { if (!window.confirm(`Remove ${value}?`)) return; try { await api(`/reserved-usernames/${encodeURIComponent(value)}`, { method: "DELETE" }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not remove username."); } }; return <section><SectionTitle icon={KeyRound} title="Reserved usernames" description="Keep protected names unavailable for normal claims." /><div className="surface mb-5 grid gap-3 rounded-2xl p-4 sm:grid-cols-[1fr_1fr_auto]"><TextInput value={username} onChange={setUsername} placeholder="username" /><TextInput value={reason} onChange={setReason} placeholder="Reason" /><Button variant="accent" onClick={() => void add()}>Reserve</Button></div>{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="surface divide-y divide-white/[.06] rounded-2xl">{items.map((item) => <div key={item.username} className="flex items-center gap-3 p-4"><span className="flex-1 text-sm text-zinc-200">@{item.username}<span className="ml-3 text-xs text-zinc-600">{item.reason || "No reason"}</span></span><Button variant="ghost" className="h-8 min-h-0 px-2 text-xs text-red-300" onClick={() => void remove(item.username)}>Remove</Button></div>)}</div></section>; }

function BadgesPanel() { const [items, setItems] = useState<any[]>([]); const [form, setForm] = useState({ id: "", name: "", description: "", color: "#9b87f5" }); const [target, setTarget] = useState(""); const [error, setError] = useState(""); const load = () => void api("/badges").then((r) => setItems(r.badges || [])).catch((e) => setError(e.message)); useEffect(load, []); const add = async () => { try { await api("/badges", { method: "POST", body: JSON.stringify(form) }); setForm({ id: "", name: "", description: "", color: "#9b87f5" }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not create badge."); } }; const assign = async (id: string) => { try { await api(`/users/${target}/badges/${id}`, { method: "PUT", body: JSON.stringify({ enabled: true }) }); } catch (e) { setError(e instanceof Error ? e.message : "Could not assign badge."); } }; return <section><SectionTitle icon={ShieldCheck} title="Badges" description="Create badges and assign them to a user UUID." /><div className="surface mb-5 grid gap-3 rounded-2xl p-4 sm:grid-cols-2"><TextInput value={form.id} onChange={(v) => setForm({ ...form, id: v })} placeholder="badge-id" /><TextInput value={form.name} onChange={(v) => setForm({ ...form, name: v })} placeholder="Badge name" /><TextInput value={form.description} onChange={(v) => setForm({ ...form, description: v })} placeholder="Description" /><div className="flex gap-2"><TextInput value={target} onChange={setTarget} placeholder="Target UUID" /><Button variant="accent" onClick={() => void add()}>Create</Button></div></div>{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{items.map((item) => <div key={item.id} className="surface rounded-2xl p-4"><p className="font-medium text-zinc-200">{item.name}</p><p className="mt-1 text-xs text-zinc-500">{item.description}</p><Button variant="subtle" className="mt-4 h-8 min-h-0 px-2 text-xs" onClick={() => void assign(item.id)} disabled={!target}>Assign</Button></div>)}</div></section>; }

function PremiumPanel() { const [items, setItems] = useState<any[]>([]); const [userId, setUserId] = useState(""); const [plan, setPlan] = useState("premium"); const [error, setError] = useState(""); const load = () => void api("/entitlements").then((r) => setItems(r.entitlements || [])).catch((e) => setError(e.message)); useEffect(load, []); const add = async () => { try { await api("/entitlements", { method: "POST", body: JSON.stringify({ user_id: userId, plan, active: true }) }); setUserId(""); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not grant entitlement."); } }; return <section><SectionTitle icon={ShieldCheck} title="Premium entitlements" description="Grant and inspect server-side premium access." /><div className="surface mb-5 flex gap-2 rounded-2xl p-4"><TextInput value={userId} onChange={setUserId} placeholder="User UUID" /><TextInput value={plan} onChange={setPlan} placeholder="Plan" /><Button variant="accent" onClick={() => void add()}>Grant</Button></div>{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="surface divide-y divide-white/[.06] rounded-2xl">{items.map((item) => <div key={item.id} className="flex items-center gap-3 p-4 text-xs"><span className="flex-1 text-zinc-300">{item.user_id}</span><span className="text-zinc-500">{item.plan}</span><span className={item.active ? "text-emerald-400" : "text-zinc-600"}>{item.active ? "Active" : "Inactive"}</span></div>)}</div></section>; }

function ReportsPanel() { const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const load = () => void api("/reports").then((r) => setItems(r.reports || [])).catch((e) => setError(e.message)); useEffect(load, []); const update = async (id: string, status: string) => { try { await api(`/reports/${id}`, { method: "PATCH", body: JSON.stringify({ status }) }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not update report."); } }; return <section><SectionTitle icon={Flag} title="Reports" description="Review and resolve community reports." />{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="surface divide-y divide-white/[.06] rounded-2xl">{items.map((item) => <div key={item.id} className="p-4"><div className="flex gap-3"><div className="flex-1"><p className="text-sm text-zinc-200">{item.reason} <span className="ml-2 text-xs text-zinc-600">{item.target_username || item.target_user_id || "unknown target"}</span></p><p className="mt-1 text-xs text-zinc-500">{item.details || "No details"}</p></div><span className="text-xs text-zinc-500">{item.status}</span></div><div className="mt-3 flex gap-2"><Button variant="ghost" className="h-8 min-h-0 px-2 text-xs" onClick={() => void update(item.id, "reviewed")}>Review</Button><Button variant="ghost" className="h-8 min-h-0 px-2 text-xs" onClick={() => void update(item.id, "resolved")}>Resolve</Button><Button variant="ghost" className="h-8 min-h-0 px-2 text-xs" onClick={() => void update(item.id, "dismissed")}>Dismiss</Button></div></div>)}{!items.length && <p className="p-8 text-center text-xs text-zinc-600">No reports.</p>}</div></section>; }

function FlagsPanel() { const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); const load = () => void api("/feature-flags").then((r) => setItems(r.flags || [])).catch((e) => setError(e.message)); useEffect(load, []); const toggle = async (item: any) => { try { await api(`/feature-flags/${encodeURIComponent(item.key)}`, { method: "PUT", body: JSON.stringify({ enabled: !item.enabled, description: item.description }) }); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not update flag."); } }; return <section><SectionTitle icon={Flag} title="Feature flags" description="Control server-side feature switches." />{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="surface divide-y divide-white/[.06] rounded-2xl">{items.map((item) => <div key={item.key} className="flex items-center gap-3 p-4"><div className="flex-1"><p className="font-mono text-sm text-zinc-200">{item.key}</p><p className="mt-1 text-xs text-zinc-600">{item.description}</p></div><Button variant={item.enabled ? "accent" : "ghost"} className="h-8 min-h-0 px-3 text-xs" onClick={() => void toggle(item)}>{item.enabled ? "Enabled" : "Disabled"}</Button></div>)}{!items.length && <p className="p-8 text-center text-xs text-zinc-600">No feature flags yet.</p>}</div></section>; }

function AuditPanel() { const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); useEffect(() => { void api("/audit-logs").then((r) => setItems(r.logs || [])).catch((e) => setError(e.message)); }, []); return <section><SectionTitle icon={Database} title="Audit logs" description="Every administrative write is recorded here." />{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="surface divide-y divide-white/[.06] rounded-2xl">{items.map((item) => <div key={item.id} className="grid gap-1 p-4 text-xs sm:grid-cols-[180px_1fr_1fr]"><span className="text-zinc-600">{new Date(item.created_at).toLocaleString()}</span><span className="font-mono text-[#b8acff]">{item.action}</span><span className="text-zinc-500">{item.target_type || "—"}: {item.target_id || "—"}</span></div>)}{!items.length && <p className="p-8 text-center text-xs text-zinc-600">No audit records yet.</p>}</div></section>; }

function BakaBoostPanel() { const [items, setItems] = useState<any[]>([]); const [error, setError] = useState(""); useEffect(() => { void api("/bakaboost").then((r) => setItems(r.connections || [])).catch((e) => setError(e.message)); }, []); return <section><SectionTitle icon={Database} title="BakaBoost connections" description="Inspect connection state without exposing provider credentials." />{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="surface divide-y divide-white/[.06] rounded-2xl">{items.map((item) => <div key={item.user_id} className="flex items-center gap-3 p-4 text-xs"><span className="flex-1 font-mono text-zinc-400">{item.user_id}</span><span className="text-zinc-500">{item.provider}</span><span className={item.status === "connected" ? "text-emerald-400" : "text-amber-300"}>{item.status}</span></div>)}{!items.length && <p className="p-8 text-center text-xs text-zinc-600">No BakaBoost connections recorded.</p>}</div></section>; }

function ThemesPanel() { const [items, setItems] = useState<any[]>([]); const [name, setName] = useState(""); const [error, setError] = useState(""); const load = () => void api("/themes").then((r) => setItems(r.themes || [])).catch((e) => setError(e.message)); useEffect(load, []); const add = async () => { try { await api("/themes", { method: "POST", body: JSON.stringify({ name, config: {}, active: true }) }); setName(""); load(); } catch (e) { setError(e instanceof Error ? e.message : "Could not save theme."); } }; return <section><SectionTitle icon={Database} title="Themes and presets" description="Manage server-side presets available to profiles." /><div className="surface mb-5 flex gap-2 rounded-2xl p-4"><TextInput value={name} onChange={setName} placeholder="Preset name" /><Button variant="accent" onClick={() => void add()}>Save preset</Button></div>{error && <p className="mb-3 text-xs text-red-300">{error}</p>}<div className="surface divide-y divide-white/[.06] rounded-2xl">{items.map((item) => <div key={item.id} className="flex items-center gap-3 p-4 text-sm"><span className="flex-1 text-zinc-300">{item.name}</span><span className={item.active ? "text-emerald-400" : "text-zinc-600"}>{item.active ? "Active" : "Inactive"}</span></div>)}{!items.length && <p className="p-8 text-center text-xs text-zinc-600">No presets yet.</p>}</div></section>; }
